replay: pause/play fonctionnel
ul-gaul/Avionique_Software pull request #49
Opened 2018-03-19 14:42 UTC by konoufo

2018-03-21 01:06 UTC, MaitreMenard requested changes

2018-03-21 01:06 UTC, MaitreMenard commented on gaul_avionique.sublime-project
> +{
Fichier à ajouter au .gitignore afin d'éviter qu'il soit suivi par git.

2018-03-21 01:06 UTC, MaitreMenard commented on gaul_avionique.sublime-workspace
> +{
Fichier à ajouter au .gitignore afin d'éviter qu'il soit suivi par git.

2018-03-21 01:06 UTC, MaitreMenard commented on BaseStation/src/consumer.py
> +import time
Import non utilisé.

2018-03-21 01:06 UTC, MaitreMenard commented on BaseStation/src/file_data_producer.py
> +    """ Producteur à partir d'une source fichier
Commentaire à retirer. Le comportement de l'attribut Event devrait être encapsulé dans des méthodes publiques avec des noms explicites (voir commentaires suivants).

2018-03-21 01:06 UTC, MaitreMenard commented on BaseStation/src/replay_controller.py
> +        self.data_producer.started_event.set()
Encapsuler ces deux lignes dans une méthode publique de la classe FileDataProducer.

2018-03-21 01:06 UTC, MaitreMenard commented on BaseStation/src/replay_controller.py
> +        self.data_producer.started_event.clear()
Encapsuler cette ligne dans une méthode publique de la classe FileDataProducer.

2018-03-21 01:13 UTC, MaitreMenard commented
En général c'est bien, mais j'ai soulevé quelques détails qui pourraient être améliorés:

- Les fichiers de Sublime Text ne devraient pas se retrouver dans le gestionnaire de version
- Les classes devraient encapsuler leur fonctionnement interne et communiquer à l'aide de leurs méthodes publiques pour éviter que des modifications dans une classe aient des répercutions dans beaucoup d'autres si on change de façon de faire.
- On essaye d'éviter d'écrire des commentaires. Il est préférable d'utiliser des noms de méthodes ou de variables décrivant explicitement le comportement.

2018-03-21 02:44 UTC, konoufo commented
Ok, je m'occupe de régler ça.

________________________________
De : Maxime Ménard <notifications@github.com>
Envoyé : mercredi 21 mars 2018 01:13:39
À : ul-gaul/Avionique_Software
Cc : konoufo; Author
Objet : Re: [ul-gaul/Avionique_Software] replay: pause/play fonctionnel (#49)


En général c'est bien, mais j'ai soulevé quelques détails qui pourraient être améliorés:

  *   Les fichiers de Sublime Text ne devraient pas se retrouver dans le gestionnaire de version
  *   Les classes devraient encapsuler leur fonctionnement interne et communiquer à l'aide de leurs méthodes publiques pour éviter que des modifications dans une classe aient des répercutions dans beaucoup d'autres si on change de façon de faire.
  *   On essaye d'éviter d'écrire des commentaires. Il est préférable d'utiliser des noms de méthodes ou de variables décrivant explicitement le comportement.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ul-gaul/Avionique_Software/pull/49#issuecomment-374809138>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AJMLjM_X0aUmzfKj3DUNOErTNTSoJG7Fks5tgalDgaJpZM4SwSZP>.

2018-03-24 03:50 UTC, konoufo commented
Je crois que ça devrait être bon.

2018-03-25 20:50 UTC, MaitreMenard approved these changes

2018-03-25 20:50 UTC, merged