Résolution du bug de la barre de progression
ul-gaul/Avionique_Software pull request #63
Opened 2018-11-02 02:08 UTC by BaboucheOne

Résolution du bug de la barre de progression

- Il est désormais possible de drag la bar de progression sans souci.
- Simplification de la formule pour trouver le pourcentage a l'horizontal.

2018-11-02 18:41 UTC, MaitreMenard requested changes

2018-11-02 18:41 UTC, MaitreMenard commented on BaseStation/src/openrocket_simulation.py
> +            raise DomainError("Le fichier de simulation " + filename + " n'a pas pu être chargé")
Le PEP8 recommande que les fichiers soient terminés par des sauts de ligne, car c'est une convention sur les systèmes Unix.

2018-11-02 18:41 UTC, MaitreMenard commented on BaseStation/src/ui/ExtendedQSlider.py
> +        super().mousePressEvent(q_mouse_event)
Même chose que le premier commentaire.

2018-11-02 18:41 UTC, MaitreMenard commented on BaseStation/src/ui/ExtendedQSlider.py
> +                new_value = q_mouse_event.x() / self.width() * 100
Ceci ne fonctionne que si le range est entre 0 et 100. Ça ne fonctionnera plus quand le range va être modifié en fonction du nombre de packets.

2018-11-02 18:41 UTC, MaitreMenard commented on BaseStation/src/ui/ExtendedQSlider.py
>                  self.setValue(self.maximum() - new_value)
L'arrondissement devrait aussi être appliqué ici.

2018-11-02 19:02 UTC, MaitreMenard commented
J'ai testé le fonctionnement de la barre et le curseur ne reste plus bloqué quand on glisse la souris au dessus. Par contre, le curseur bloque encore parfois quand on le drag. J'ai l'impression qu'on va devoir reimplémenter la méthode _mouseMoveEvent_ (voir: http://doc.qt.io/qt-5/qwidget.html#mouseMoveEvent).

2018-11-03 03:32 UTC, BaboucheOne commented on BaseStation/src/ui/ExtendedQSlider.py
>                  self.setValue(self.maximum() - new_value)
Effectivement je n avais pas pris en compte le nombre de packets sur le moment.

2018-11-03 03:36 UTC, BaboucheOne commented
Comment test-tu la barre ? 
Apres plusieurs essai, la barre répond comme demandé.

2018-11-07 20:12 UTC, MaitreMenard approved these changes

2018-11-07 20:14 UTC, MaitreMenard commented
Dans le fichier openrocket_simulation.py, tu as mis le saut de ligne à la fin de la ligne 17 et non à la fin de la ligne 18. À part ça tout est beau.

2018-11-07 20:44 UTC, merged