Injection des préférences dans le codebase + configuration du port COM
ul-gaul/Avionique_Software pull request #75
Opened 2019-02-24 22:15 UTC by konoufo

2019-05-19 10:22 UTC, BaboucheOne requested changes
Rien de tres important a changer. Il faut cependant résoudre les conflit avec la branche de dev.

2019-05-19 10:22 UTC, BaboucheOne commented on BaseStation/src/ui/config_controller.py
> +            print(settings)
N'oublis pas d’enlever le 'print'. Si toute fois c'est important, signale le pour que je l’ajoute dans la console.

2019-05-19 23:50 UTC, konoufo commented on BaseStation/src/ui/config_controller.py
> +            print(settings)
C'était pour débugger à la base. Donc on peut s'en passer.

2019-05-20 16:27 UTC, BaboucheOne approved these changes
C'est bon pour moi

2019-05-23 04:50 UTC, MaitreMenard requested changes

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/configdialog.py
>      def set_stylesheet(self, stylesheet_path):
C'est une bonne pratique d'utiliser le le mot clé `with` pour gérer l'ouverture d'un fichier en Python, car le fichier est automatiquement fermé tout de suite après la fin du bloc contenu dans le `with`.

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
> +        return set(list(self.get_parsed_sections() + self.get_dynamic_sections()))
Il n'est pas nécessaire d'appeler la fonction `list` ici, car la concaténation du résultat des deux méthodes donne déjà une liste.

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
> +            parsed_names = [name for (name, _) in settings[:parsed_end]]
Ici, `settings[:parsed_end]` équivaut à la liste entière.

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
> +            ('port_com', (self._get_serial_port_options(), 'list', 'Port COM'))]}
Le commentaire pour l'objet _Setting_ s'applique ici aussi. De plus, pourquoi créer un dictionnaire, pour ensuite aller chercher son unique valeur et la retourner?

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
> +                        settings.remove(settings[doublon_pos])
Dans quel cas peut-il y avoir des doublons? Aussi, pourquoi ajouter tous les _dynamic_settings_ avant de parcourir la liste à nouveau pour retirer les doublons? Pourquoi ne pas simplement ajouter le setting que s'il n'est pas déjà présent?

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
>      def get_settings(self, section_name=None):
Cette méthode devrait être refactorée, car il est assez difficile de comprendre son fonctionnement. Tu pourrais entre-autre te créer un objet _Setting_ et les retourner dans la liste plutôt qu'un tuple dans un tuple. Cela simplifierait le code et le rendrait plus expressif.

2019-05-23 04:50 UTC, MaitreMenard commented on BaseStation/src/ui/configdialog.py
> +                    input_el = QListWidget()
Tu pourrais faire une interface _SettingInput_ possédant deux implémentations: _ListSettingInput_ et _LineSettingInput_. Ces objets pourraient hériter de leur widget correspondant pour en exposer les fonctionnalités, en plus de remplacer les dictionnaires qui sont ajoutés dans `self.inputs`. De plus, chacun d'eux serait libre d'implémenter une méthode `get_value` pour remplacer celle de la ligne 129 et ainsi enlever le besoin de conserver la variable `input_type`.

2019-05-23 23:55 UTC, konoufo commented on BaseStation/src/ui/configdialog.py
>      def set_stylesheet(self, stylesheet_path):
wow; j'en reviens pas d'avoir laissé traîner une ouverture de fichier mais `with` is the way to go.

2019-05-24 00:01 UTC, konoufo commented on BaseStation/src/ui/config_controller.py
> +        return set(list(self.get_parsed_sections() + self.get_dynamic_sections()))
ouais j'avais un truc en tête quand j'ai fait ça c'était que `self.get_parsed_sections()` et `self.get_dynamic_sections()` retourne des collections un peu spéciales. Mais bon pour le moment effectivement ça sert à rien.

2019-05-24 00:03 UTC, konoufo commented on BaseStation/src/ui/config_controller.py
> +            ('port_com', (self._get_serial_port_options(), 'list', 'Port COM'))]}
En anticipation qu'il y ait d'autres settings de ce genre dans le futur ?

2019-05-24 00:20 UTC, konoufo commented on BaseStation/src/ui/config_controller.py
> +                        settings.remove(settings[doublon_pos])
> Dans quel cas peut-il y avoir des doublons?

Il y a doublon quand, dans le fichier ini, on renseigne un `serial_port=COM1` par exemple alors que le `serial_port` est aussi considéré comme une setting dynamique (dont le choix dépend de l'état du système durant l'exécution). En bref quand une _parsed_setting_ a le même nom qu'une _dynamic_setting_.

> Aussi, pourquoi ajouter tous les dynamic_settings avant de parcourir la liste à nouveau pour retirer les doublons? Pourquoi ne pas simplement ajouter le setting que s'il n'est pas déjà présent?

C'est un peu l'inverse qui est souhaité. On veut que la _dynamic_setting_ soit toujours prépondérante. On ne retire jamais une _dynamic_setting_ mais une _parsed_setting_ si elle a le même nom qu'une _dynamic_setting_. On pourrait certainement vérifier toutes les __parsed_settings__ avant de les ajouter du coup mais ça ne fait pas grande différence.

2019-05-24 00:21 UTC, konoufo commented on BaseStation/src/ui/config_controller.py
>      def get_settings(self, section_name=None):
Ouais ça serait plus expressif.

2019-05-24 00:26 UTC, konoufo commented on BaseStation/src/ui/configdialog.py
> +                    input_el = QListWidget()
> Tu pourrais faire une interface SettingInput possédant deux implémentations: ListSettingInput et LineSettingInput. Ces objets pourraient hériter de leur widget correspondant pour en exposer les fonctionnalités, en plus de remplacer les dictionnaires qui sont ajoutés dans self.inputs.

Très bonne idée!
>De plus, chacun d'eux serait libre d'implémenter une méthode get_value pour remplacer celle de la ligne 129 et ainsi enlever le besoin de conserver la variable input_type

Du coup, qui serait responsable de la création des objets _ListSettingInput_ et _LineSettingInput_ ? Le _ConfigController_ ?

2019-05-24 00:28 UTC, konoufo commented on BaseStation/src/ui/configdialog.py
> +                    input_el = QListWidget()
Bon, en même temps ils pourraient être créés dans _ConfigDialog_. Très bien.

2019-06-04 03:48 UTC, MaitreMenard commented on BaseStation/src/ui/config_controller.py
> +                        settings.remove(settings[doublon_pos])
Ah ok, je comprends :) Ça a du sens!

2019-06-04 03:58 UTC, MaitreMenard approved these changes

2019-06-04 04:00 UTC, MaitreMenard commented
Il ne reste que la gestion du fichier CSS avec `with` à corriger, mais sinon c'est très bien!

2019-06-09 01:50 UTC, merged