Switch mode
ul-gaul/Avionique_Software pull request #76
Opened 2019-03-24 15:59 UTC by MaitreMenard

2019-03-29 03:55 UTC, BaboucheOne requested changes
Tres bien. J'ai juste repéré quelque petites choses qui pourrais être amélioré.
De plus j'ai testé ta branche, et tout est bon. J'ai tout essayé pour avoir des bugs, mais rien a faire !

2019-03-29 03:55 UTC, BaboucheOne commented on BaseStation/src/realtime/serial_data_producer.py
>          if len(ports) <= 0:
'ports' étant une liste, pourquoi ne pas juste vérifier si `len(ports) == 0`

2019-03-29 03:55 UTC, BaboucheOne commented on BaseStation/src/save.py
> +            return SaveStatus.CANCELLED
Le 'else" peut être évité. Tu pourrais directement le mettre a la fin. Cela serait plus simple a lire et directement savoir ce que la méthode retourne par défaut.

2019-03-29 03:55 UTC, BaboucheOne commented on BaseStation/src/ui/mainwindow.py
>      def set_stylesheet(self, stylesheet_path):
Il faudrait importer le ficher "utils.py" et utiliser la méthode 'read_stylesheet'.
On évite une duplication de code.

2019-03-29 03:55 UTC, BaboucheOne commented on BaseStation/src/ui/menu_bar.py
Pourquoi pas créer une méthode qui permet de générer les 'action' ?
Elle permettrai de réduire le considérablement nombre de lignes, car chaque déclaration différente d'action utilise au global les même arguments. De plus, cette méthode ajouterai donc chaque 'action' dans le 'files_menu'

2019-04-07 16:27 UTC, konoufo commented on BaseStation/src/real_time_controller.py
> +                self.data_producer.clear()
Pour être cohérent if faudrait peut être remplacer la méthode `DataProducer.clear()` par `DataProducer.reset()`.

2019-04-07 16:29 UTC, konoufo commented on BaseStation/src/realtime/serial_data_producer.py
>          if len(ports) <= 0:
`if ports:` serait encore plus pythonique

2019-04-07 16:54 UTC, konoufo commented on BaseStation/src/save.py
> +            return SaveStatus.CANCELLED
L36 et L40

2019-04-07 17:52 UTC, konoufo commented on BaseStation/tests/test_replay_controller.py
> +        self.file_data_producer.restart.assert_called_with()
Utiliser plutôt `assert_called()` ?

2019-04-07 17:55 UTC, konoufo reviewed
C'est bon; pas grande chose à changer.

2019-04-07 18:42 UTC, MaitreMenard commented on BaseStation/src/real_time_controller.py
> +                self.data_producer.clear()
"reset" a du sens pour le `consumer` et le `data_widget`, car dans les deux cas, la méthode les remet dans leur état initial. Cependant, pour `data_producer`, la méthode ne fait que supprimer les données, elle ne change pas l'état du thread d'acquisition. "clear_rocket_packets" serait donc un nom plus approprié que "reset", tout en étant plus expressif que simplement "clear".

2019-04-07 19:05 UTC, MaitreMenard commented on BaseStation/src/ui/menu_bar.py
Après une tentative de refactoring, il a été convenu avec @BaboucheOne qu'une méthode pour générer les actions réduit la répétition, mais rend le code moins lisible. En effet, une telle méthode requiert 5 paramètres, dont des strings assez longues, et leur rôle respectif n'est pas clair lors de l'appel.

2019-04-07 19:09 UTC, BaboucheOne approved these changes
C'est bon pour moi

2019-04-07 19:09 UTC, merged