Add fields to rocket packet 2019
ul-gaul/Avionique_Software pull request #83
Opened 2019-05-17 13:34 UTC by BaboucheOne

Les champs suivants sont maintenant pris en compte dans le rocket packets 2019:
- Indicateur NS, EW
- Magnetometre
- Pression
- Temps UTC

Tous les tests passent. Il faudrait cependant vérifier avec le simulateur Arduino si tout est bon.
(J’espère retrouver le mien sous peux)

2019-05-19 16:03 UTC, MaitreMenard requested changes

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/src/rocket_packet/rocket_packet.py
> +        #magnetometre pression milli-gauss
Le magnétomètre ne mesure pas une pression, mais l'intensité des champs magnétiques.

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/src/rocket_packet/rocket_packet.py
> +        self.UTCtime = b''
Ce champ devrait être un double.

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/src/rocket_packet/rocket_packet_parser_2019.py
>          return [packet.time_stamp, packet.latitude, packet.longitude, b'N', b'W', 0.0, packet.altitude, 0,
N'oublie pas d'ajouter les champs _UTCTime_, _NSIndicator_, _EWIndicator_ et _pressure_ dans la liste.

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/tests/rocket_packet/test_rocket_packet_parser_2019.py
> +        rocket_packet.UTCtime = self.UTC_TIME
Tu pourrais mettre des valeurs non nulles dans les constantes définies dans le haut du fichier pour s'assurer que le _RocketPacket_ est bien construit. En effet, le _RocketPacket_ initialise tous ses champs à 0 dans son constructeur, alors le test ne permet pas de vérifier si le _RocketPacketParser_ a bien fait son travail.

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/src/resources/flight4.csv
> +"time_stamp","angular_speed_x","angular_speed_y","angular_speed_z","acceleration_x","acceleration_y","acceleration_z","altitude","latitude","longitude","temperature","quaternion_w","quaternion_x","qu
As-tu essayé de jouer ce vol en mode replay? Je doute que ça fonctionne correctement, puisque ce fichier contient des champs de 2017 ou 2018 que le _RocketPacketParser2019_ ne support pas (ex: les acquisition_board_state). De plus, les champs ne sont pas dans l'ordre attendu (ex: UTCTime devrait être le 6e champ et non le dernier).

2019-05-19 16:03 UTC, MaitreMenard commented on BaseStation/tests/resources/test2019.csv
> +"time_stamp","angular_speed_x","angular_speed_y","angular_speed_z","acceleration_x","acceleration_y","acceleration_z","altitude","latitude","longitude","temperature","quaternion_w","quaternion_x","qu
Commentaire similaire à celui pour le fichier _flight4.csv_. De plus, tu pourrais simplement remplacer le contenu de _test.csv_ pour des données de 2019 afin qu'on n'ait qu'un seul fichier de test.

2019-05-19 16:06 UTC, MaitreMenard commented
Le simulateur Arduino retourne présentement des valeurs nulles ou des données bidon pour les champs que tu as ajoutés. Ça serait bien si il pouvait envoyé des données qui ont plus de sens.

2019-05-20 16:28 UTC, BaboucheOne commented on BaseStation/src/rocket_packet/rocket_packet.py
> +        #magnetometre pression milli-gauss
Houla ! c'est moi qui est oublier d'enlever cela

2019-06-01 21:06 UTC, MaitreMenard approved these changes

2019-06-01 21:06 UTC, MaitreMenard commented
Tout est en ordre, tu peux faire le merge.

2019-06-02 19:08 UTC, merged